name: Deploy to Cloud Functions

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Generate requirements.txt
        run: |
          python -m pip install "poetry==1.3.2"
          poetry export -f requirements.txt --without-hashes > requirements.txt

      - id: auth
        name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT }}

      - id: deploy
        name: Deploy to Cloud Functions
        uses: google-github-actions/deploy-cloud-functions@v1
        with:
          name: ${{ secrets.FUNCTION_NAME }}
          runtime: python312
          entry_point: main
          memory_mb: 256
          region: asia-east1
          project_id: ${{ secrets.PROJECT_ID }}
          timeout: 90
          min_instances: 0
          max_instances: 1
          event_trigger_type: google.pubsub.topic.publish
          event_trigger_resource: projects/${{ secrets.PROJECT_ID }}/topics/${{ secrets.TOPIC_ID }}
          env_vars: ${{ secrets.ENV_VARS }}
